# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='creat_date',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='news',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
