# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171004_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='create_date',
        ),
    ]
